title: Atomiv
tagline: 10x Software Template
url: https://atomiv.com

include: ['_pages']

exclude:
  - README.md

gems:
  - jekyll-sitemap

permalink: /:year/:month/:day/:title
# permalink: pretty

# if colelctions not at root level
# collections_dir: my_collections

collections:
  pages:
    output: true
    permalink: /:path
    vversion2: 3
    # permalink: /:collection/:name
  authors:
    output: true
  templates:
    output: true
    # layout: templates-layout
    # permalink: /:collection/:name
    # permalink: /:title

templates-categories:
  # configuration array to store templates order
  - two
    # href=""
    # suburl: /category-one/one
  - one
    # suburl: /category-two/four


sass:
  # where to search for Sass files, if the folder is called '_scss'
  # sass_dir: assets/css
  # sass_dir: _scss
  sass_dir: _scss
  style: compressed
  
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# You can also change the default _sass/ directory to a custom directory in your _config.yml:
# sass:
#   sass_dir: _lib
#   or ... sass_dir: _sass


# Enable minification on your compiled CSS by updating your _config.yml to include:
# sass:
#   style: compressed