title: Atomiv
tagline: 10x Software Template
url: https://atomiv.com

include: ['_pages']
# exclude: ['README.md']

exclude:
  - README.md

gems:
  - jekyll-sitemap

permalink: /:year/:month/:day/:title
# permalink: pretty

# if colelctions not at root level
collections_dir: content

collections:
  staff_members:
    output: true
    # default permalink
    # permalink: /:collection/:name
    order:
      - jelena.md
      - ana.md
      - jane.md
    # title: The Grey Parrot Stories
    # sequence: 1
  pages:
    output: true
    permalink: /:path
    vversion2: 3
    # permalink: /:collection/:name
  authors:
    output: true
  # templates:
  #   output: true

  
    # layout: templates-layout
    # permalink: /:collection/:name
    # permalink: /:title


# Now you can remove layout from the front matter of all pages and posts.
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"    






templates-categories:
  # configuration array to store templates order
  - two
    # href=""
    # suburl: /category-one/one
  - one
    # suburl: /category-two/four


sass:
  # where to search for Sass files, if the folder is called '_scss'
  # sass_dir: assets/css
  # sass_dir: _scss
  sass_dir: _scss
  style: compressed
  
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# You can also change the default _sass/ directory to a custom directory in your _config.yml:
# sass:
#   sass_dir: _lib
#   or ... sass_dir: _sass


# Enable minification on your compiled CSS by updating your _config.yml to include:
# sass:
#   style: compressed




# {% assign collections = site.collections | sort: 'sequence' %}
# {% for collection in site.collections %}
#   {% if collection.title %}
# * {{ collection.title | escape }}
#   {% endif %}
# {% endfor %}